spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

server:
  port: 8000
  servlet:
    context-path: /gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    fetch-registry: true
    register-with-eureka: true
