server:
  port: 8000
  servlet:
    context-path: /gateway

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
      routes:
        - id: userservice
          uri: http://localhost:8002
          predicates:
            - Path=/user/**

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    fetch-registry: true
    register-with-eureka: true
